### ISSUE TITLE
Where is the upstream of django-auth-ldap?

### ISSUE THREAD

**Issue by guettli** [rbarrois/python-ldap#11] opened 2015-06-05 09:04 UTC
The pypi page looks empty:

https://pypi.python.org/pypi/django-auth-ldap

Where is the current upstream repo of this project?

**Comment by rbarrois** [comment] 2015-06-05 09:37
This is a duplicate of #10; look at http://bitbucket.org/psagers/django-auth-ldap/.

**Closed as completed by rbarrois** 2015-06-05 09:37 UTC
